package Session3.exception;

import java.util.Scanner;

public class ExceptionHandlingDemo {

	public static void main(String[] args) {
		Scanner sc = new Scanner(System.in);
		try {
			System.out.println("Enter num1:");
			int num1=sc.nextInt();
			System.out.println("Enter num2:");
			int num2=sc.nextInt();
			System.out.println("Result: "+num1/num2);
		}
		catch (Exception e) {
			System.out.println("Provide positive value");
			e.printStackTrace();
		}
	}

}
